# Generated by Django 2.2.14 on 2020-07-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='google_sheet_googlesheetpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, help_text='For admins only - displayed in the plugins sidebar', max_length=256)),
                ('link', models.URLField(help_text='In order to get this link open your sheet and in the menu select File -> Publish to the web')),
                ('width', models.CharField(default='100%', help_text='In pixels (500px) or percentages', max_length=32)),
                ('height', models.CharField(default='721px', help_text='In pixels or percentages', max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
