# Generated by Django 2.2.14 on 2020-07-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetpluginmodel',
            name='is_show_headers',
            field=models.BooleanField(default=False, verbose_name='Show table headers'),
        ),
    ]
