# Generated by Django 2.2.14 on 2020-08-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_hero_with_content', '0002_rename_field_spacing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardherowithcontent',
            old_name='hero_element_size',
            new_name='content_wrapper_size',
        ),
    ]
