# Generated by Django 2.2.16 on 2020-09-19 16:34

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import link_all.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepluginmodel',
            name='link_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='imagepluginmodel',
            name='link_is_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open in a new tab'),
        ),
        migrations.AlterField(
            model_name='imagepluginmodel',
            name='link_label',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='imagepluginmodel',
            name='link_type',
            field=enumfields.fields.EnumField(null=True, default='url', enum=link_all.models.LinkType, max_length=64),
        ),
    ]
