# Generated by Django 2.2.16 on 2020-09-24 19:30

from django.db import migrations
import enumfields.fields
import link_all.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_add_support_for_latest_link_all_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepluginmodel',
            name='link_type',
            field=enumfields.fields.EnumField(default='url', enum=link_all.models.LinkType, max_length=64),
        ),
    ]
