# Generated by Django 2.2.12 on 2020-05-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpluginmodel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
