# Generated by Django 2.2.12 on 2020-05-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_list', '0002_add_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpluginmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
