# Generated by Django 2.2.14 on 2020-07-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSlidesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='google_slides_googleslidespluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('link', models.URLField()),
                ('width', models.CharField(default='100%', help_text='In pixels (500px) or percentages', max_length=32)),
                ('height', models.CharField(default='721px', help_text='In pixels (500px) or percentages', max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
