# Generated by Django 2.2.14 on 2020-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_slides', '0002_add_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleslidespluginmodel',
            name='height',
            field=models.CharField(default='550px', help_text='In pixels or percentages', max_length=32),
        ),
    ]
