# Generated by Django 2.2.12 on 2020-05-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailchimpPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='mailchimp_mailchimppluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('server_location_code', models.CharField(help_text="eg 'us18'", max_length=32)),
                ('organization_id', models.CharField(max_length=1024)),
                ('list_id', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
