# Generated by Django 2.2.12 on 2020-05-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBarPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nav_bar_navbarpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('is_full_width', models.BooleanField(default=False, verbose_name='Full width')),
                ('is_enable_search_bar', models.BooleanField(default=True, verbose_name='Enable search bar')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
