# Generated by Django 2.2.12 on 2020-05-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarpluginmodel',
            name='is_enable_search_bar',
            field=models.BooleanField(default=True, verbose_name='Show search input'),
        ),
    ]
