# Generated by Django 2.2.14 on 2020-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_bar', '0002_change_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarpluginmodel',
            name='is_use_default_menu',
            field=models.BooleanField(default=True, help_text='You can either use the default menu or compose a custom one by adding child Menu plugins inside this Navigation bar plugin', verbose_name='Use default menu'),
        ),
    ]
