# Generated by Django 2.2.14 on 2020-07-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_bar', '0006_remove_old_navbar_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarpluginmodel',
            name='is_use_multi_level_menu_on_mobile',
            field=models.BooleanField(default=False, help_text='This menu shows more than 1 level of children.', verbose_name='Use multi-level menu on mobile'),
        ),
    ]
