# Generated by Django 2.2.16 on 2020-09-17 16:00

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import link_all.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nav_bar', '0007_add_field_is_use_multi_level_menu_on_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemmodel',
            name='link',
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_button_color',
            field=enumfields.fields.EnumField(blank=True, default='primary', enum=link_all.models.ButtonColor, max_length=64, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_instance_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_is_button',
            field=models.BooleanField(default=False, verbose_name='Render as button'),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_is_button_full_width',
            field=models.BooleanField(default=False, verbose_name='Full width'),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_is_button_outlined',
            field=models.BooleanField(default=False, verbose_name='Transparent body'),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_is_open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Open in a new tab'),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_label',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_type',
            field=enumfields.fields.EnumField(default='url', enum=link_all.models.LinkType, max_length=64),
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='link_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='navbarpluginmodel',
            name='is_use_multi_level_menu_on_mobile',
            field=models.BooleanField(default=False, help_text='The multi-level menu shows around 3-4 levels of children.', verbose_name='Use multi-level menu on mobile'),
        ),
    ]
