# Generated by Django 2.2.12 on 2020-06-05 20:15

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('card', '0002_add_model_card_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpluginmodel',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cardpluginmodel',
            name='internal_link',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.Page'),
        ),
    ]
