# Generated by Django 2.2.13 on 2020-06-06 19:28

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_add_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpluginmodel',
            name='internal_link',
            field=cms.models.fields.PageField(blank=True, help_text='You can configure either an internal or external link (below) for that card.', null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.Page'),
        ),
    ]
