# Generated by Django 2.2.16 on 2020-09-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_list', '0002_use_fk_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpluginmodel',
            name='person',
            field=models.ForeignKey(help_text="The person record that's attached to this plugin is global, ie if you change a photo of a person it's going to change on all related Person plugins", on_delete=django.db.models.deletion.CASCADE, to='person_list.Person'),
        ),
    ]
