# Generated by Django 2.2.12 on 2020-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heading_element', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headingplugin',
            name='heading_type',
        ),
        migrations.AlterField(
            model_name='headingplugin',
            name='text',
            field=models.CharField(default='-', max_length=2048),
            preserve_default=False,
        ),
    ]
