# Generated by Django 2.2.12 on 2020-05-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailchimppluginmodel',
            name='font_size',
            field=models.FloatField(default=1, help_text='In rem'),
        ),
    ]
