# Generated by Django 2.2.12 on 2020-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0002_add_font_size_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailchimppluginmodel',
            name='is_enable_border',
            field=models.BooleanField(default=True, verbose_name='Show input border'),
        ),
    ]
