# Generated by Django 2.2.16 on 2020-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0004_add_width_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailchimppluginmodel',
            name='list_id',
            field=models.CharField(help_text='eg d652eb1a9c', max_length=1024),
        ),
        migrations.AlterField(
            model_name='mailchimppluginmodel',
            name='organization_id',
            field=models.CharField(help_text='eg 0d235948217a55858a0e810c4', max_length=1024),
        ),
        migrations.AlterField(
            model_name='mailchimppluginmodel',
            name='server_location_code',
            field=models.CharField(help_text='eg us18', max_length=32),
        ),
    ]
