# Generated by Django 2.2.13 on 2020-06-06 19:13

import backend.plugins.section_with_image_background.models
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import enumfields.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('section_with_image_background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionwithimagebackgroundpluginmodel',
            name='rich_text_editor_background',
            field=enumfields.fields.EnumField(default='white', enum=backend.plugins.section_with_image_background.models.RichTextEditorBackground, help_text="You can set the background of a rich text editor used inside this plugin, for readability purposes. For example if your background image is black it's better to set background in the editor to be black as well.", max_length=10),
        ),
        migrations.AlterField(
            model_name='sectionwithimagebackgroundpluginmodel',
            name='background_image',
            field=filer.fields.image.FilerImageField(help_text='Minimal width is 1920px, default minimal height is 350px, but can be configured below.', on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
