# Generated by Django 2.2.13 on 2020-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfigtranslation',
            name='site_subname',
            field=models.CharField(blank=True, help_text='Shown in the navbar below the name.', max_length=1024),
        ),
    ]
