# Generated by Django 3.1.7 on 2021-03-02 19:33

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('site_config', '0002_add_field_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_config_favicon', to='filer.file'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_config_logo', to='filer.file'),
        ),
    ]
