# Generated by Django 2.2.14 on 2020-07-18 19:46

import backend.plugins.nav_bar.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_add_field_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='navbar_default',
            field=enumfields.fields.EnumField(default='normal', enum=backend.plugins.nav_bar.models.NavBarType, help_text='This type of navbar will be set for newly created pages', max_length=10),
        ),
    ]
